<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListsRepository extends EntityRepository
{
    /**
     * get list by type
     *
     * @param $type
     * @return array
     */
    public function getList($type)
    {
        $elements = $this->getEntityManager()->getRepository('AppBundle:Lists')->findByType($type);
        $list=array();
        foreach ($elements as $element) {
            $list[]=array(
                'id'=>$element->getId(),
                'name'=>$element->getName(),
            );
        }
        return $list;
    }
}
