<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserNotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationsRepository extends EntityRepository
{
    public function getNotifications($user_id){
        $elements = $this->getEntityManager()->getRepository('AppBundle:UserNotifications')->findByUserId($user_id);
        $list=array();
        foreach ($elements as $element) {
            $list[]=$element->getNotificationId();
        }
        return $list;
    }
    public function setNotifications($user_id,$notifications)
    {
        $elements = $this->getEntityManager()->getRepository('AppBundle:UserNotifications')->findByUserId($user_id);
        $em=$this->getEntityManager();
        if(is_array($elements))
        foreach ($elements as $element) {
            $em->remove($element);
        }
        foreach ($notifications as $key=>$value) {
            $notification=new UserNotifications();
            $notification->setNotificationId($value);
            $notification->setUserId($user_id);
            $em->persist($notification);
        }
        $em->flush();
    }
}
